/********************************************************
 *  NSDictionary+MultiKeys.h
 *
 *  Created by J2Objc(Json to objc) on {{date}}.
 *  Copyright (c) 2013 WesleyYang. All rights reserved.
 *
 *  THIS FILE IS AUTO-GENERATED BY J2OBJC. DO NOT TRY TO
 *  MODIFY IT UNLESS YOU ARE NOT RELYING ON J2OBJC FOR
 *  MAKING ANY CHANGES!
 *
 ********************************************************/

#import <Foundation/Foundation.h>

#define DEBUG_NSDICTIONARY_MULTIKEYS    1



@interface NSDictionary (MultiKeys)


- (id)objectForPossibleKeys:(NSArray*)pkeys;

@end
