#line 2 "Json2ObjcLexer.mm"

#line 4 "Json2ObjcLexer.mm"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 136
#define YY_END_OF_BUFFER 137
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[447] =
    {   0,
        0,    0,  137,  135,  134,  134,  122,  135,    3,  128,
      121,  135,  116,  117,  126,  125,  113,  124,  120,  127,
       80,   80,  114,  110,  129,  115,  130,  133,  135,   77,
       77,   77,   77,   77,   77,   77,  118,  119,  131,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,  111,  132,  112,  123,
      109,    0,   84,    0,   95,  112,  104,   96,    0,   86,
        0,   93,  101,   91,  102,   92,  103,    0,   82,    1,
        2,   94,   83,   79,    0,   80,    0,   80,  119,  111,
      118,  100,  106,  108,  107,   99,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   77,   77,   77,    0,    0,   73,   77,
       77,   97,   77,   77,   77,   77,   77,   77,   77,   41,
       77,   77,   77,   77,   77,   77,   77,   49,   77,   77,
       74,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   98,  105,   88,    0,   82,   82,    0,   83,
       79,    0,   81,   78,   90,   89,    0,   85,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   77,
       77,    0,   86,    0,   77,   71,   77,   77,   77,   77,

       77,   77,   77,   77,   77,   77,   77,   77,   77,   47,
       77,   50,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   69,    0,
       82,    0,   82,    0,   83,   81,   78,   17,    0,    0,
        0,    0,    9,    0,    0,    0,   22,   15,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    8,   67,   77,   72,   34,   66,   77,   36,   37,
       77,   77,   77,   77,   43,   44,   77,   77,   77,   48,
       51,   77,   77,   77,   77,   77,   77,   77,   77,   70,
       77,   77,   77,   63,   77,   77,    0,   82,   11,   16,

        0,    0,    0,    0,    0,   10,    0,    0,    0,   14,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   76,
       77,   35,   38,   77,   77,   77,   77,   75,   46,   77,
       77,   54,   77,   77,   77,   77,   77,   77,   61,   77,
       77,   65,    0,    0,    0,   23,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   77,   77,   77,   42,   45,   77,   53,
       55,   56,   57,   58,   59,   77,   77,   77,   13,    0,
        0,    0,   30,   12,    0,    0,    0,    0,    0,    0,
        0,   25,    0,    0,    0,   18,    0,    0,   68,   77,

       40,   77,   60,   77,   77,    5,    0,   33,    0,    0,
        0,   24,    0,    0,    0,    4,    0,    0,    0,    0,
       39,   52,   62,   64,    7,    0,    0,   29,   27,    0,
       21,   28,    6,   31,    0,    0,   19,   26,    0,    0,
       32,    0,    0,    0,   20,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   35,   35,   36,   35,   37,   38,   39,
       40,   41,   42,   43,   44,   35,   35,   45,   46,   35,
       47,   48,   49,   50,   35,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   35,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   76,   77,   78,   79,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[80] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[453] =
    {   0,
        0,    0,  599,  600,  600,  600,  575,   75,  600,   58,
       75,   76,  600,  600,  574,   71,  600,   72,   70,   80,
       83,   90,  572,  600,   93,  572,   67,  600,  156,    0,
      556,  566,  102,  554,  550,  559,  600,  600,  566,  518,
       53,   54,   67,   69,   82,  523,   73,  522,  521,  529,
       90,   73,  520,  518,  523,  525,  600,   81,  600,  600,
      600,  120,  600,  576,  600,  600,  600,  600,  126,  128,
      136,  600,  600,  600,  600,  600,  600,  562,  146,  600,
      600,  600,  186,  209,  154,  193,    0,  230,  600,  600,
      600,  554,  600,  600,  600,  553,  145,  544,  543,  535,

      541,  530,  509,  495,  505,  512,  511,   92,  500,  116,
      509,   97,  496,    0,  524,  525,  158,  148,    0,  516,
      517,  600,  489,  493,  501,  487,  503,  490,  496,  481,
      482,  479,  479,  486,  482,  478,  475,    0,  474,  479,
        0,  118,  477,  109,  141,  481,  469,  473,  111,  171,
      478,  468,  600,  600,  600,  220,  600,  237,  262,  600,
      240,  180,  270,  242,  600,  600,  183,  600,  532,  491,
      506,  490,  194,  495,  479,  466,  190,  459,  476,  461,
      456,  455,  455,  193,  470,  228,  460,  457,  458,  482,
      475,  203,  210,  257,  485,    0,  451,  453,  462,  457,

      444,  203,  459,  457,  453,  445,  451,  437,  453,    0,
      439,    0,  445,  442,  430,  432,  435,  442,  427,  425,
      425,  438,  437,  427,  431,  435,  437,  426,    0,  264,
      286,  296,  600,  289,  298,  600,  283,  600,  456,  442,
      440,  444,  600,  414,  430,  416,  600,  600,  425,  417,
      422,  417,  406,  403,  116,  412,  402,  406,  400,  414,
      399,  600,    0,  436,    0,    0,  411,  405,    0,    0,
      395,  404,  392,  400,    0,    0,  393,  404,  389,    0,
        0,  389,  389,  386,  399,  389,  393,  398,  397,    0,
      395,  385,  390,    0,  377,  390,  302,  305,  413,  600,

      412,  404,  373,  378,  385,  383,  382,  369,  371,  600,
      383,  378,  139,  373,  240,  367,  363,  376,  370,    0,
      376,    0,    0,  363,  364,  369,  360,    0,    0,  353,
      358,    0,  366,  363,  365,  348,  358,  360,    0,  351,
      354,    0,  371,  369,  373,  600,  350,  353,  340,  344,
      349,  341,  334,  335,  348,  347,  346,  330,  330,  333,
      332,  325,  338,  329,  321,  321,    0,    0,  334,    0,
        0,    0,    0,    0,    0,  332,  332,  325,  600,  342,
      340,  319,  600,  600,  310,  313,  312,  307,  291,  289,
      293,  600,  287,  300,  284,  600,  287,  282,    0,  294,

        0,  281,    0,  292,  290,  600,  312,  600,  277,  286,
      277,  600,  262,  280,  272,  600,  278,  274,  261,  266,
        0,    0,    0,    0,  600,  244,  235,  600,  600,  233,
      600,  600,  600,  600,  192,  214,  600,  600,  204,  181,
      600,  157,  127,   47,  600,  600,  366,  370,  372,   90,
      376,  380
    } ;

static yyconst flex_int16_t yy_def[453] =
    {   0,
      446,    1,  446,  446,  446,  446,  446,  447,  446,  446,
      446,  448,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  449,
      449,  449,  449,  449,  449,  449,  446,  446,  446,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  446,  446,  446,  446,
      446,  447,  446,  447,  446,  446,  446,  446,  448,  448,
      448,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  450,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  451,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  449,  449,  449,  447,  452,  449,  449,
      449,  446,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  450,  446,  446,  451,  446,  451,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  449,
      449,  452,  452,  452,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  449,  449,

      449,  449,  449,  449,  449,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      449,  449,  449,  449,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,    0,  446,  446,  446,  446,
      446,  446
    } ;

static yyconst flex_int16_t yy_nxt[680] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   30,   30,
       30,   32,   30,   30,   30,   33,   34,   30,   30,   30,
       30,   30,   35,   30,   30,   36,   37,    4,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   30,   47,   30,
       48,   30,   49,   30,   30,   30,   50,   51,   52,   53,
       54,   55,   30,   56,   30,   57,   58,   59,   60,   63,
       65,   66,   67,   73,   70,   78,   75,   79,   79,   95,
       96,   80,  164,   74,   76,   77,   81,   68,   83,   90,

       84,   84,   82,  153,  126,   83,  117,   88,   88,  445,
      118,  127,   91,   85,   92,   93,  124,  128,   86,  125,
       85,  129,   64,   71,   63,   86,   86,   87,  138,  131,
      130,  132,  134,   86,   70,  139,   70,   85,  446,  147,
       69,  133,  135,   86,   85,  136,  148,  143,  144,  168,
       86,  187,   86,  180,  181,   87,  193,  154,  145,   86,
       97,  146,   63,   79,   79,  217,  162,   64,  162,  224,
      188,  163,  163,   71,  214,   71,  156,  157,  225,  183,
      312,  157,  184,  218,  313,  185,  215,  168,   98,   99,
      444,  219,  169,  355,  100,  194,  101,  163,  163,  102,

      156,  157,  356,  158,  158,   64,  157,  220,  103,  104,
      105,  193,  106,  107,  108,  443,  159,  160,  193,  109,
      110,  160,  111,  112,   83,  113,   84,   84,   86,  226,
      169,  227,  230,  241,  230,  242,   86,  231,  231,   85,
      159,  160,  246,  247,  161,   83,  160,   88,   88,  442,
      194,  254,  161,   86,  158,  158,  255,  194,  441,  446,
       85,  192,   86,   85,  440,   86,  439,  232,  233,  161,
      271,  272,  233,   86,  234,  161,  234,  237,  161,  235,
      235,  231,  231,  161,   85,  237,  438,  163,  163,  437,
       86,  232,  233,  257,  358,  258,  259,  233,  359,   86,

      161,  236,  237,  231,  231,  236,  235,  235,  297,  161,
      297,  237,  436,  298,  298,  235,  235,  157,  237,  298,
      298,  157,  298,  298,  435,  236,  237,  434,  433,  160,
      236,  432,  431,  160,  430,  429,  233,  428,  427,  426,
      233,  157,  425,  237,  424,  423,  157,  422,  421,  420,
      419,  418,  237,  160,  417,  416,  415,  414,  160,  413,
      233,  412,  411,  410,  409,  233,   62,   62,   62,   62,
       69,  408,   69,   69,  114,  114,  167,  167,  167,  167,
      192,  407,  192,  192,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,

      390,  389,  388,  387,  386,  385,  384,  383,  382,  381,
      380,  379,  378,  377,  376,  375,  374,  373,  372,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  357,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,

      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  256,  253,  252,  251,  250,  249,  248,  245,  244,
      243,  240,  239,  238,  446,  229,  228,  223,  222,  221,
      216,  213,  212,  211,  210,  209,  208,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      191,  190,  189,  186,  182,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  166,  165,  155,  446,  152,
      151,  150,  149,  142,  141,  140,  137,  123,  122,  121,
      120,  119,  116,  115,   94,   89,   72,   61,  446,    3,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446
    } ;

static yyconst flex_int16_t yy_chk[680] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
       10,   10,   11,   16,   12,   19,   18,   19,   19,   27,
       27,   20,  450,   16,   18,   18,   20,   11,   21,   25,

       21,   21,   20,   58,   42,   22,   33,   22,   22,  444,
       33,   42,   25,   21,   25,   25,   41,   42,   21,   41,
       22,   43,    8,   12,   62,   22,   21,   21,   47,   44,
       43,   44,   45,   22,   69,   47,   70,   21,   71,   52,
       71,   44,   45,   21,   22,   45,   52,   51,   51,   97,
       22,  112,   21,  108,  108,   21,  118,   58,   51,   22,
       29,   51,  117,   79,   79,  144,   85,   62,   85,  149,
      112,   85,   85,   69,  142,   70,   79,   79,  149,  110,
      255,   79,  110,  144,  255,  110,  142,  167,   29,   29,
      443,  145,   97,  313,   29,  118,   29,  162,  162,   29,

       79,   79,  313,   83,   83,  117,   79,  145,   29,   29,
       29,  192,   29,   29,   29,  442,   83,   83,  193,   29,
       29,   83,   29,   29,   84,   29,   84,   84,   86,  150,
      167,  150,  156,  173,  156,  173,   86,  156,  156,   84,
       83,   83,  177,  177,   84,   88,   83,   88,   88,  440,
      192,  184,   84,   86,  158,  158,  184,  193,  439,  194,
       88,  194,   86,   84,  436,   88,  435,  158,  158,   84,
      202,  202,  158,   88,  159,  161,  159,  164,   84,  159,
      159,  230,  230,  161,   88,  164,  430,  163,  163,  427,
       88,  158,  158,  186,  315,  186,  186,  158,  315,   88,

      161,  163,  164,  231,  231,  163,  234,  234,  232,  161,
      232,  164,  426,  232,  232,  235,  235,  231,  237,  297,
      297,  231,  298,  298,  420,  163,  237,  419,  418,  235,
      163,  417,  415,  235,  414,  413,  298,  411,  410,  409,
      298,  231,  407,  237,  405,  404,  231,  402,  400,  398,
      397,  395,  237,  235,  394,  393,  391,  390,  235,  389,
      298,  388,  387,  386,  385,  298,  447,  447,  447,  447,
      448,  382,  448,  448,  449,  449,  451,  451,  451,  451,
      452,  381,  452,  452,  380,  378,  377,  376,  369,  366,
      365,  364,  363,  362,  361,  360,  359,  358,  357,  356,

      355,  354,  353,  352,  351,  350,  349,  348,  347,  345,
      344,  343,  341,  340,  338,  337,  336,  335,  334,  333,
      331,  330,  327,  326,  325,  324,  321,  319,  318,  317,
      316,  314,  312,  311,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  299,  296,  295,  293,  292,  291,  289,
      288,  287,  286,  285,  284,  283,  282,  279,  278,  277,
      274,  273,  272,  271,  268,  267,  264,  261,  260,  259,
      258,  257,  256,  254,  253,  252,  251,  250,  249,  246,
      245,  244,  242,  241,  240,  239,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,

      214,  213,  211,  209,  208,  207,  206,  205,  204,  203,
      201,  200,  199,  198,  197,  195,  191,  190,  189,  188,
      187,  185,  183,  182,  181,  180,  179,  178,  176,  175,
      174,  172,  171,  170,  169,  152,  151,  148,  147,  146,
      143,  140,  139,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  121,  120,
      116,  115,  113,  111,  109,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   96,   92,   78,   64,   56,
       55,   54,   53,   50,   49,   48,   46,   40,   39,   36,
       35,   34,   32,   31,   26,   23,   15,    7,    3,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "json2objc.l"
#line 2 "json2objc.l"

#include "ParserHeader.h"
#include "Json2ObjcParser.h"

//#include <malloc.h>

    #ifndef  DEBUG_BISON
    #define NSLog(...)
    #define printf(...)
    #endif
    

extern char _VCurrentIdentifier[512];
void comment();
void linecomment();
void preCompiler();
void keyword();
int check_type();
void _VSetDataToScan(const char *someData);
extern BOOL _VIsKnownTypeName();

static const char * _VCurrentDataBytes = NULL;
static NSData *_VCurrentData = nil;
static int _VCurrentDataBytesIndex = 0;

#ifdef _WIN32

/* Windows doesn't define the isatty() function.
   As we always read from a file, we can easily
   provide the following simple implementation: */

int isatty (int fd)
{
    return 0;
}
#endif

#line 51 "json2objc.l"
#include <stdio.h>
#include "Json2ObjcParser.h"

void count();
#line 793 "Json2ObjcLexer.mm"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 57 "json2objc.l"

#line 977 "Json2ObjcLexer.mm"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 447 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 600 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 58 "json2objc.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "json2objc.l"
{ linecomment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "json2objc.l"
{ preCompiler();}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "json2objc.l"
{ count();keyword(); return(REQUEST);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "json2objc.l"
{ count();keyword(); return(REQUEST);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "json2objc.l"
{ count();keyword(); return(RESPONSE);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "json2objc.l"
{ count();keyword(); return(RESPONSE);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "json2objc.l"
{ count();keyword(); return(URL);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "json2objc.l"
{ count();keyword(); return(URL);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "json2objc.l"
{ count();keyword(); return(HEADER);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "json2objc.l"
{ count();keyword(); return(HEADER);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 73 "json2objc.l"
{ count();keyword(); return(HEADER);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 74 "json2objc.l"
{ count();keyword(); return(HEADER);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "json2objc.l"
{ count();keyword(); return(POST);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "json2objc.l"
{ count();keyword(); return(GET);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "json2objc.l"
{ count();keyword(); return(POST);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "json2objc.l"
{ count();keyword(); return(GET);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "json2objc.l"
{ count();keyword(); return(RETURN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "json2objc.l"
{ count();keyword(); return(INTERFACE);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "json2objc.l"
{ count();keyword(); return(IMPLEMENTATION);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "json2objc.l"
{ count();keyword(); return(PROTOCOL);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 87 "json2objc.l"
{ count();keyword(); return(END);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 88 "json2objc.l"
{ count();keyword(); return(CLASS);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "json2objc.l"
{ count();keyword(); return(PRIVATE);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "json2objc.l"
{ count();keyword(); return(PUBLIC);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "json2objc.l"
{ count();keyword(); return(PROTECTED);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "json2objc.l"
{ count();keyword(); return(PROPERTY);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 94 "json2objc.l"
{ count();keyword(); return(REQUIRED);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "json2objc.l"
{ count();keyword(); return(OPTIONAL);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 97 "json2objc.l"
{ count();keyword(); return(ENCODE);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 98 "json2objc.l"
{ count();keyword(); return(SELECTOR);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "json2objc.l"
{ count();keyword();return(SYNTHESIZE);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "json2objc.l"
{ count();keyword(); return(DYNAMIC);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "json2objc.l"
{ count();keyword(); return(AUTO); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "json2objc.l"
{ count();keyword(); return(BREAK); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "json2objc.l"
{ count();keyword(); return(CASE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "json2objc.l"
{ count();keyword(); return(CHAR); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "json2objc.l"
{ count();keyword(); return(CONST); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 108 "json2objc.l"
{ count();keyword(); return(CONTINUE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 109 "json2objc.l"
{ count();keyword(); return(DEFAULT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "json2objc.l"
{ count();keyword(); return(DO); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "json2objc.l"
{ count();keyword(); return(DOUBLE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "json2objc.l"
{ count();keyword(); return(ELSE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "json2objc.l"
{ count();keyword(); return(ENUM); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "json2objc.l"
{ count();keyword(); return(EXTERN); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 115 "json2objc.l"
{ count();keyword(); return(FLOAT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 116 "json2objc.l"
{ count();keyword(); return(FOR); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 117 "json2objc.l"
{ count();keyword(); return(GOTO); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 118 "json2objc.l"
{ count();keyword(); return(IF); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 119 "json2objc.l"
{ count();keyword(); return(INT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 120 "json2objc.l"
{ count();keyword(); return(LONG); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 121 "json2objc.l"
{ count();keyword(); return(REGISTER); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 122 "json2objc.l"
{ count();keyword(); return(RETURN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 123 "json2objc.l"
{ count();keyword(); return(SHORT); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 124 "json2objc.l"
{ count();keyword(); return(SIGNED); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 125 "json2objc.l"
{ count();keyword(); return(SIZEOF); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 126 "json2objc.l"
{ count();keyword(); return(STATIC); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 127 "json2objc.l"
{ count();keyword(); return(STRUCT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 128 "json2objc.l"
{ count();keyword(); return(SWITCH); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 129 "json2objc.l"
{ count();keyword(); return(TYPEDEF); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "json2objc.l"
{ count();keyword(); return(UNION); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 131 "json2objc.l"
{ count();keyword(); return(UNSIGNED); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 132 "json2objc.l"
{ count();keyword(); return(VOID); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 133 "json2objc.l"
{ count();keyword(); return(VOLATILE); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 134 "json2objc.l"
{ count();keyword(); return(WHILE); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "json2objc.l"
{ count();keyword(); return(SBOOL); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "json2objc.l"
{ count();keyword(); return(SBOOL); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 "json2objc.l"
{ count();keyword(); return(SBOOL); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "json2objc.l"
{ count();keyword(); return(SYES); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "json2objc.l"
{ count();keyword(); return(SYES); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "json2objc.l"
{ count();keyword(); return(SYES); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "json2objc.l"
{ count();keyword(); return(SYES); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "json2objc.l"
{ count();keyword(); return(SNO); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 "json2objc.l"
{ count();keyword(); return(SNO); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "json2objc.l"
{ count();keyword(); return(SNO); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "json2objc.l"
{ count();keyword(); return(SNO); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 148 "json2objc.l"
{ count(); return(check_type()); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 150 "json2objc.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 151 "json2objc.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 152 "json2objc.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 154 "json2objc.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 155 "json2objc.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 156 "json2objc.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 158 "json2objc.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 159 "json2objc.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 160 "json2objc.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 161 "json2objc.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 163 "json2objc.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 164 "json2objc.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 165 "json2objc.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 166 "json2objc.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 167 "json2objc.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 168 "json2objc.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 169 "json2objc.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 170 "json2objc.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 171 "json2objc.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 172 "json2objc.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 173 "json2objc.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 174 "json2objc.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 175 "json2objc.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 176 "json2objc.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 177 "json2objc.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 178 "json2objc.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 179 "json2objc.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 180 "json2objc.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 181 "json2objc.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 182 "json2objc.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 183 "json2objc.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 184 "json2objc.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 185 "json2objc.l"
{ count(); return(';'); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 186 "json2objc.l"
{ count(); return('{'); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 187 "json2objc.l"
{ count(); return('}'); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 188 "json2objc.l"
{ count(); return(','); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 189 "json2objc.l"
{ count(); return(':'); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 190 "json2objc.l"
{ count(); return('='); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 191 "json2objc.l"
{ count(); return('('); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 192 "json2objc.l"
{ count(); return(')'); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 193 "json2objc.l"
{ count(); return('['); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 194 "json2objc.l"
{ count(); return(']'); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 195 "json2objc.l"
{ count(); return('.'); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 196 "json2objc.l"
{ count(); return('&'); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 197 "json2objc.l"
{ count(); return('!'); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 198 "json2objc.l"
{ count(); return('~'); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 199 "json2objc.l"
{ count(); return('-'); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 200 "json2objc.l"
{ count(); return('+'); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 201 "json2objc.l"
{ count(); return('*'); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 202 "json2objc.l"
{ count(); return('/'); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 203 "json2objc.l"
{ count(); return('%'); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 204 "json2objc.l"
{ count(); return('<'); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 205 "json2objc.l"
{ count(); return('>'); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 206 "json2objc.l"
{ count(); return('^'); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 207 "json2objc.l"
{ count(); return('|'); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 208 "json2objc.l"
{ count(); return('?'); }
	YY_BREAK
case 134:
/* rule 134 can match eol */
YY_RULE_SETUP
#line 210 "json2objc.l"
{ count(); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 211 "json2objc.l"
{ count();/* ignore bad characters */ }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 213 "json2objc.l"
ECHO;
	YY_BREAK
#line 1745 "Json2ObjcLexer.mm"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 447 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 447 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 446);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 213 "json2objc.l"


#define TAB_WORD 1
void keyword()
{
//    REC(RECTYPE_KEYWORD, @"",yylloc);

}

void comment()
{
    yylloc.first_line = yylloc.last_line;
    yylloc.first_column = yylloc.last_column;
    yylloc.last_column+=2;
    char c, c1;

loop:
    while ((c = yyinput()) != '*' && c != 0){
                putchar(c);
        if(c=='\n'){
            yylloc.last_column=0;
            yylloc.last_line++;
        } else if (c == '\t'){
            yylloc.last_column+=TAB_WORD-(yylloc.last_column%TAB_WORD);
            
        }else{
            yylloc.last_column++;

        }
    }
    yylloc.last_column++;

        if ((c1 = yyinput()) != '/' && c != 0)
        {
                unput(c1);
                goto loop;
        }

    if (c != 0){
            putchar(c1);
        yylloc.last_column+=1;

    }
    REC(RECTYPE_COMMENT,@"",yylloc);
//    printf("[CommentFromC:%d,%d Line:%d,%d]",yylloc.first_column,yylloc.last_column,yylloc.first_line,yylloc.last_line);
}

void linecomment()
{
    yylloc.first_line = yylloc.last_line;
    yylloc.first_column = yylloc.last_column;
    yylloc.last_column+=2;
    char c;
    while ((c = yyinput()) != '\n' && c != 0){
        if (c == '\t'){
            yylloc.last_column+=TAB_WORD-(yylloc.last_column%TAB_WORD);
            
        }else{
            yylloc.last_column++;
        }
    }
    unput(c);
//    printf("[LCommentFromC:%d,%d Line:%d,%d]",yylloc.first_column,yylloc.last_column,yylloc.first_line,yylloc.last_line);
    REC(RECTYPE_COMMENT,@"",yylloc);

}

void preCompiler()
{
    yylloc.first_line = yylloc.last_line;
    yylloc.first_column = yylloc.last_column;
    yylloc.last_column+=1;
    NSString *preString=@"";
    NSString *followString=@"";
    NSString **string = &preString;
    char c;
    while ((c = yyinput()) != '\n' && c != 0){
        if(c==' ' || c=='\t')string = &followString;
        
        *string = [*string stringByAppendingFormat:@"%c",c];
        if (c == '\t'){
            yylloc.last_column+=TAB_WORD-(yylloc.last_column%TAB_WORD);
            
        }else{
            yylloc.last_column++;
        }
    }
    unput(c);
    
    
    
    NSLog(@"[PreCompiler:[%@|%@]%d,%d Line:%d,%d]",preString,followString,yylloc.first_column,yylloc.last_column,yylloc.first_line,yylloc.last_line);
    REC(RECTYPE_PRECOMPILER,@"",yylloc);
    
    if ([preString isEqualToString:@"import"] || [preString isEqualToString:@"include"]) {
        YYLTYPE loc;
        loc.first_line=yylloc.first_line;
        loc.last_line = yylloc.last_line;
        loc.first_column = preString.length+yylloc.first_column+1;
        loc.last_column = yylloc.last_column;
        REC(RECTYPE_STRING,@"",loc);
    }
}

int column = 0;

void count()
{
    yylloc.first_line = yylloc.last_line;
    yylloc.first_column = yylloc.last_column;
    
    int i;
    
    for (i = 0; yytext[i] != '\0'; i++){
        if (yytext[i] == '\n'){
            column = 0;
            yylloc.last_column=0;
            yylloc.last_line++;
        }
        else if (yytext[i] == '\t'){
            column += TAB_WORD - (column % TAB_WORD);
            yylloc.last_column+=TAB_WORD-(yylloc.last_column%TAB_WORD);
            
        }
        else{
            column++;
            yylloc.last_column++;
        }
    }
        yylval.sval = [NSString stringWithCString:yytext encoding:NSUTF8StringEncoding];

//    ECHO;
    
}


int check_type()
{
  strncpy(_VCurrentIdentifier, yytext, 511);

//printf("\ncheck_type:%s , isKNOWN:%d\n",yytext,_VIsKnownTypeName(yytext));
//    char *newVal = (char*)malloc(sizeof(char)*strlen(yytext));
//    yylval.sval = strcpy(newVal,yytext);
    yylval.sval = [NSString stringWithCString:_VCurrentIdentifier];
  if(_VIsKnownTypeName()) {
    return(TYPE_NAME);
  } else {
    return(IDENTIFIER);
  }
}


/* inits the global string to the one we will parse */
void _VSetDataToScan(const char *someData)
{
    yylloc.first_column=yylloc.last_column = 0;
    yylloc.first_line = yylloc.last_line = 1;
    
//  [someData retain];
//  [_VCurrentData release];
//  _VCurrentData = someData;
  _VCurrentDataBytesIndex = 0;
//  _VCurrentDataBytes = (const char*)[_VCurrentData bytes];
    _VCurrentDataBytes = someData;
  if (_VCurrentDataBytes != NULL) {
    yy_scan_string(_VCurrentDataBytes);
  }
}

/* tells lex there's really no more input when we're done */
int yywrap() {
    return 1;
}
