/********************************************************
 *  {{class_name}}.h
 *  {{project_name}}
 *
 *  Created by J2Objc(Json to objc) on {{date}}.
 *  Copyright (c) 2013 WesleyYang. All rights reserved.
 *
 *  THIS FILE IS AUTO-GENERATED BY J2OBJC. DO NOT TRY TO
 *  MODIFY IT UNLESS YOU ARE NOT RELYING ON J2OBJC FOR
 *  MAKING ANY CHANGES!
 *
 ********************************************************/


#import <Foundation/Foundation.h>
{{#import_headers}}
#import "{{import_header}}.h"{{/import_headers}}

@interface {{class_name}} : NSObject


{{#properties}}
/*
 * @property {{property_name}}
 * @description: {{class_name}}'s {{property_name}}
 */
@property ({{property_attributes}})     {{property_type}}       {{property_name}};

{{/properties}}


/*
 * @param dataDic : input dictionary
 * @return : object created from dictionary
 */
+ ({{class_name}}*)objectFromDictionary:(NSDictionary*)dataDic;

/*
 * @param dataDic : input dictionary
 * @return : array of {{class_name}} created from dictionary
 */
+ (NSArray*)arrayFromDictionaryArray:(NSArray*)dataDicArray;


@end


